let cards = [
  { name: "Archer Queen", value: 5, imgSrc: './clash_card_imgs/archer-queen.png' },
  { name: "Archers", value: 3, imgSrc: './clash_card_imgs/archers.png' },
  { name: "Arrows", value: 3, imgSrc: './clash_card_imgs/arrows.png' },
  { name: "Baby Dragon", value: 4, imgSrc: './clash_card_imgs/baby-dragon.png' },
  { name: "Bandit", value: 3, imgSrc: './clash_card_imgs/bandit.png' },
  { name: "Barbarian Barrel", value: 2, imgSrc: './clash_card_imgs/barbarian-barrel.png' },
  { name: "Barbarian Hut", value: 7, imgSrc: './clash_card_imgs/barbarian-hut.png' },
  { name: "Balloon", value: 5, imgSrc: './clash_card_imgs/balloon.png' },
  { name: "Barbarians", value: 5, imgSrc: './clash_card_imgs/barbarians.png' },
  { name: "Battle Healer", value: 4, imgSrc: './clash_card_imgs/battle-healer.png' },
  { name: "Battle Ram", value: 4, imgSrc: './clash_card_imgs/battle-ram.png' },
  { name: "Bats", value: 2, imgSrc: './clash_card_imgs/bats.png' },
  { name: "Bomber", value: 2, imgSrc: './clash_card_imgs/bomber.png' },
  { name: "Bomb Tower", value: 4, imgSrc: './clash_card_imgs/bomb-tower.png' },
  { name: "Bowler", value: 5, imgSrc: './clash_card_imgs/bowler.png' },
  { name: "Cannon", value: 3, imgSrc: './clash_card_imgs/cannon.png' },
  { name: "Cannon Cart", value: 5, imgSrc: './clash_card_imgs/cannon-cart.png' },
  { name: "Clone", value: 3, imgSrc: './clash_card_imgs/clone.png' },
  { name: "Dark Prince", value: 4, imgSrc: './clash_card_imgs/dark-prince.png' },
  { name: "Dart Goblin", value: 3, imgSrc: './clash_card_imgs/dart-goblin.png' },
  { name: "Earthquake", value: 3, imgSrc: './clash_card_imgs/earthquake.png' },
  { name: "Electro Dragon", value: 5, imgSrc: './clash_card_imgs/electro-dragon.png' },
  { name: "Electro Giant", value: 7, imgSrc: './clash_card_imgs/electro-giant.png' },
  { name: "Electro Spirit", value: 1, imgSrc: './clash_card_imgs/electro-spirit.png' },
  { name: "Electro Wizard", value: 4, imgSrc: './clash_card_imgs/electro-wizard.png' },
  { name: "Elite Barbarians", value: 6, imgSrc: './clash_card_imgs/elite-barbarians.png' },
  { name: "Elixir Collector", value: 6, imgSrc: './clash_card_imgs/elixir-collector.png' },
  { name: "Executioner", value: 5, imgSrc: './clash_card_imgs/executioner.png' },
  { name: "Fireball", value: 4, imgSrc: './clash_card_imgs/fireball.png' },
  { name: "Firecracker", value: 3, imgSrc: './clash_card_imgs/firecracker.png' },
  { name: "Fire Spirit", value: 1, imgSrc: './clash_card_imgs/fire-spirits.png' },
  { name: "Fisherman", value: 3, imgSrc: './clash_card_imgs/fisherman.png' },
  { name: "Flying Machine", value: 4, imgSrc: './clash_card_imgs/flying-machine.png' },
  { name: "Freeze", value: 4, imgSrc: './clash_card_imgs/freeze.png' },
  { name: "Furnace", value: 4, imgSrc: './clash_card_imgs/furnace.png' },
  { name: "Giant", value: 5, imgSrc: './clash_card_imgs/giant.png' },
  { name: "Giant Skeleton", value: 6, imgSrc: './clash_card_imgs/giant-skeleton.png' },
  { name: "Giant Snowball", value: 2, imgSrc: './clash_card_imgs/giant-snowball.png' },
  { name: "Goblin Barrel", value: 3, imgSrc: './clash_card_imgs/goblin-barrel.png' },
  { name: "Goblin Cage", value: 4, imgSrc: './clash_card_imgs/goblin-cage.png' },
  { name: "Goblin Drill", value: 4, imgSrc: './clash_card_imgs/goblin-drill.png' },
  { name: "Goblin Gang", value: 3, imgSrc: './clash_card_imgs/goblin-gang.png' },
  { name: "Goblin Giant", value: 6, imgSrc: './clash_card_imgs/goblin-giant.png' },
  { name: "Goblin Hut", value: 4, imgSrc: './clash_card_imgs/goblin-hut.png' },
  { name: "Goblins", value: 2, imgSrc: './clash_card_imgs/goblins.png' },
  { name: "Golden Knight", value: 4, imgSrc: './clash_card_imgs/golden-knight.png' },
  { name: "Golem", value: 8, imgSrc: './clash_card_imgs/golem.png' },
  { name: "Graveyard", value: 5, imgSrc: './clash_card_imgs/graveyard.png' },
  { name: "Guards", value: 3, imgSrc: './clash_card_imgs/guards.png' },
  { name: "Heal Spirit", value: 1, imgSrc: './clash_card_imgs/heal-spirit.png' },
  { name: "Hog Rider", value: 4, imgSrc: './clash_card_imgs/hog-rider.png' },
  { name: "Hunter", value: 4, imgSrc: './clash_card_imgs/hunter.png' },
  { name: "Ice Golem", value: 2, imgSrc: './clash_card_imgs/ice-golem.png' },
  { name: "Ice Spirit", value: 1, imgSrc: './clash_card_imgs/ice-spirit.png' },
  { name: "Ice Wizard", value: 3, imgSrc: './clash_card_imgs/ice-wizard.png' },
  { name: "Inferno Dragon", value: 4, imgSrc: './clash_card_imgs/inferno-dragon.png' },
  { name: "Inferno Tower", value: 5, imgSrc: './clash_card_imgs/inferno-tower.png' },
  { name: "Knight", value: 3, imgSrc: './clash_card_imgs/knight.png' },
  { name: "Lava Hound", value: 7, imgSrc: './clash_card_imgs/lava-hound.png' },
  { name: "Lightning", value: 6, imgSrc: './clash_card_imgs/lightning.png' },
  { name: "Lumberjack", value: 4, imgSrc: './clash_card_imgs/lumberjack.png' },
  { name: "Magic Archer", value: 4, imgSrc: './clash_card_imgs/magic-archer.png' },
  { name: "Mega Minion", value: 3, imgSrc: './clash_card_imgs/mega-minion.png' },
  { name: "Mega Knight", value: 7, imgSrc: './clash_card_imgs/mega-knight.png' },
  { name: "Miner", value: 3, imgSrc: './clash_card_imgs/miner.png' },
  { name: "Mighty Miner", value: 5, imgSrc: './clash_card_imgs/mighty-miner.png' },
  { name: "Mini P.E.K.K.A", value: 4, imgSrc: './clash_card_imgs/mini-pekka.png' },
  { name: "Minions", value: 3, imgSrc: './clash_card_imgs/minions.png' },
  { name: "Minion Horde", value: 5, imgSrc: './clash_card_imgs/minion-horde.png' },
  { name: "Mirror", value: 1, imgSrc: './clash_card_imgs/mirror.png' },
  { name: "Monk", value: 5, imgSrc: './clash_card_imgs/monk.png' },
  { name: "Mortar", value: 4, imgSrc: './clash_card_imgs/mortar.png' },
  { name: "Mother Witch", value: 4, imgSrc: './clash_card_imgs/mother-witch.png' },
  { name: "Night Witch", value: 4, imgSrc: './clash_card_imgs/night-witch.png' },
  { name: "P.E.K.K.A", value: 7, imgSrc: './clash_card_imgs/pekka.png' },
  { name: "Phoenix", value: 4, imgSrc: './clash_card_imgs/phoenix.png' },
  { name: "Poison", value: 4, imgSrc: './clash_card_imgs/poison.png' },
  { name: "Prince", value: 5, imgSrc: './clash_card_imgs/prince.png' },
  { name: "Princess", value: 3, imgSrc: './clash_card_imgs/princess.png' },
  { name: "Rage", value: 2, imgSrc: './clash_card_imgs/rage.png' },
  { name: "Ram Rider", value: 5, imgSrc: './clash_card_imgs/ram-rider.png' },
  { name: "Rascals", value: 5, imgSrc: './clash_card_imgs/rascals.png' },
  { name: "Rocket", value: 6, imgSrc: './clash_card_imgs/rocket.png' },
  { name: "Royal Delivery", value: 3, imgSrc: './clash_card_imgs/royal-delivery.png' },
  { name: "Royal Giant", value: 6, imgSrc: './clash_card_imgs/royal-giant.png' },
  { name: "Royal Ghost", value: 3, imgSrc: './clash_card_imgs/royal-ghost.png' },
  { name: "Royal Hogs", value: 5, imgSrc: './clash_card_imgs/royal-hogs.png' },
  { name: "Royal Recruits", value: 7, imgSrc: './clash_card_imgs/royal-recruits.png' },
  { name: "Skeleton Army", value: 3, imgSrc: './clash_card_imgs/skeleton-army.png' },
  { name: "Skeleton Barrel", value: 3, imgSrc: './clash_card_imgs/skeleton-barrel.png' },
  { name: "Skeleton Dragons", value: 4, imgSrc: './clash_card_imgs/skeleton-dragons.png' },
  { name: "Skeleton King", value: 4, imgSrc: './clash_card_imgs/skeleton-king.png' },
  { name: "Skeletons", value: 1, imgSrc: './clash_card_imgs/skeletons.png' },
  { name: "Sparky", value: 6, imgSrc: './clash_card_imgs/sparky.png' },
  { name: "Spear Goblins", value: 2, imgSrc: './clash_card_imgs/spear-goblins.png' },
  { name: "Tesla", value: 4, imgSrc: './clash_card_imgs/tesla.png' },
  { name: "The Log", value: 2, imgSrc: './clash_card_imgs/the-log.png' },
  { name: "Three Musketeers", value: 9, imgSrc: './clash_card_imgs/three-musketeers.png' },
  { name: "Tornado", value: 3, imgSrc: './clash_card_imgs/tornado.png' },
  { name: "Tombstone", value: 3, imgSrc: './clash_card_imgs/tombstone.png' },
  { name: "Valkyrie", value: 4, imgSrc: './clash_card_imgs/valkyrie.png' },
  { name: "Wall Breakers", value: 2, imgSrc: './clash_card_imgs/wall-breakers.png' },
  { name: "Witch", value: 5, imgSrc: './clash_card_imgs/witch.png' },
  { name: "Wizard", value: 5, imgSrc: './clash_card_imgs/wizard.png' },
  { name: "X-Bow", value: 6, imgSrc: './clash_card_imgs/x-bow.png' },
  { name: "Zappies", value: 4, imgSrc: './clash_card_imgs/zappies.png' },
  { name: "Zap", value: 2, imgSrc: './clash_card_imgs/zap.png' },
  { name: "Berserker", value: 2, imgSrc: './clash_card_imgs/berserker.png' },
  { name: "Suspicious Bush", value: 2, imgSrc: './clash_card_imgs/sus-bush.png' },
  { name: "Goblin Curse", value: 2, imgSrc: './clash_card_imgs/goblin-curse.png' },
  { name: "Elixir Golem", value: 3, imgSrc: './clash_card_imgs/elixir-golem.png' },
  { name: "Void", value: 3, imgSrc: './clash_card_imgs/void.png' },
  { name: "Goblinstein", value: 5, imgSrc: './clash_card_imgs/goblinstein.png' },
  { name: "Goblin Demolisher", value: 4, imgSrc: './clash_card_imgs/goblin-demolisher.png' },
  { name: "Goblin Machine", value: 5, imgSrc: './clash_card_imgs/goblin-machine.png' },
  { name: "Rune Giant", value: 4, imgSrc: './clash_card_imgs/rune-giant.png' },
  { name: "Boss Bandit", value: 6, imgSrc: './clash_card_imgs/boss-bandit.png' }
]

cards = cards.sort((a, b) => a.value - b.value)
 
